apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: mkdocs
  title: Mkdocs
  description: Mkdocs of backstage
  tags:
    - mkdocs
spec:
  owner: backstage
  templater: cookiecutter
  type: website
  path: '.'
  schema:
    required:
      - component_id
      - description
    properties:
      component_id:
        title: Name
        type: string
        description: Unique name of the component
      description:
        title: Description
        type: string
        description: Help others understand what this website is for.